##服务##
[Service]
##服务类型##
##可选项："tcp"/"http"
service_type= "tcp"

##服务端口号##
tcp-port = "2333"

http-port = "9091"

##过期策略##
[ExpireStrategy]
##过期策略类型##
##可选项："LRUAll"/"RandAll"/"RandVolatile"
strategy = "LRUAll"

##内存限制阈值##
##以M为单位，配置100，表示内存限制为100M
MemoryThreshold = 100   #单位M

##定期删除过期缓存周期##
##以second为单位,配置5，表示每隔5s扫描缓存并删除过期键值对
ExpireCycle = 5         #单位s

##默认键值对过期时间##
##以second为单位
DefaultExpireTime = 0

##持久化##
[FDB]
##持久化备份间隔时间##
##以second为单位，配置5，表示每个5s备份一次缓存
FDBDuration = 5         #单位s
FileName = "dump2.fdb"

[Node]
Node = "127.0.0.2"
Cluster = "127.0.0.1"